
- name: workaround for getting home folder
  shell: "grep {{ ansible_user }} /etc/passwd | awk -F: '{print $6}'"
  register: user_home_folder

- debug:
    var: user_home_folder.stdout

- name: Create a data folder for all containers
  file:
    path: "{{ user_home_folder.stdout }}/data/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ filebeat_container_name }}"
    - "{{ logstash_container_name }}"
    - "{{ elasticsearch_container_name }}"
    - "{{ kibana_container_name }}"
    - "{{ nginx_container_name }}/conf.d/"
    - "{{ nginx_container_name }}/ssl/"

- name: Create Docker Network
  docker_network:
    name: "{{ docker_network }}"
