- name: Create a elasticsearch container
  docker_container:
    name: "{{ elasticsearch_container_name }}"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ user_home_folder.stdout }}/data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
