- name: Create a elasticsearch container
  docker_container:
    name: "{{ elasticsearch_container_name }}"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    state: started
    restart_policy: always
    volumes:
      - "{{ user_home_folder.stdout }}/data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    dns_servers: 127.0.0.1
  register: my_var

- name: Add a container to a network, leaving existing containers connected
  docker_network:
    name: "{{ docker_network }}"
    connected:
      - "{{ elasticsearch_container_name }}"
    appends: yes


- debug:
    var: my_var.ansible_facts.docker_container.NetworkSettings.Networks.bridge.IPAddress
