- name: ssl certificates
  shell: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt -subj /C=IL/ST=IL/L=IL/O=Demo/OU=DevOps/CN=Demo/emailAddress=d.m@g.com"
  args:
    chdir: "{{ user_home_folder.stdout }}/data/nginx/ssl/"

- name: nginx kibana conf
  template:
    src: kibana.conf.j2
    dest:  "{{ user_home_folder.stdout }}/data/nginx/conf.d/kibana.conf"

- htpasswd:
    path: "{{ user_home_folder.stdout }}/data/nginx/htpasswd"
    name: pipl
    password: 'pipl'
    mode: 0644

- name: Create a nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network.Name }}"
    volumes:
      - "{{ user_home_folder.stdout }}/data/nginx/conf.d/:/etc/nginx/conf.d/:ro"
      - "{{ user_home_folder.stdout }}/data/nginx/htpasswd:/etc/nginx/htpasswd:ro"
      - "{{ user_home_folder.stdout }}/data/nginx/ssl/:/etc/ssl/nginx/:ro"
