- name: Create a kibana container
  docker_container:
    name: "{{ kibana_container_name }}"
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network.Name }}"

