- name: Create config file for logstash
  template:
    src: pipeline.yml.j2
    dest: "{{ user_home_folder.stdout }}/data/logstash/pipeline.yml"

- name: copy pipelines
  copy:
    src: pipelines
    dest: "{{ user_home_folder.stdout }}/data/logstash/"

- name: Create a logstash container
  docker_container:
    name: "{{ logstash_container_name }}"
    image: docker.elastic.co/logstash/logstash-oss:6.3.0
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network.Name }}"
    volumes:
      - "{{ user_home_folder.stdout }}/data/logstash/pipeline.yml:/etc/logstash/conf.d/pipeline.yml:ro"
      - "{{ user_home_folder.stdout }}/data/logstash/pipelines/:/etc/logstash/pipelines/:ro"

